this = _this select 0;
if (!local this) exitWith {};

removeAllWeapons this;
removeAllItems this;
removeAllAssignedItems this;
removeUniform this;
removeVest this;
removeBackpack this;
removeHeadgear this;
removeGoggles this;
this forceAddUniform "U_B_CombatUniform_mcam";
this addItemToUniform "B_IR_Grenade";
for "_i" from 1 to 2 do {this addItemToUniform "SmokeShell";};
for "_i" from 1 to 2 do {this addItemToUniform "HandGrenade";};
for "_i" from 1 to 2 do {this addItemToUniform "Chemlight_blue";};
this addVest "V_PlateCarrier2_rgr";
for "_i" from 1 to 4 do {this addItemToVest "FirstAidKit";};
this addItemToVest "16Rnd_9x21_Mag";
for "_i" from 1 to 8 do {this addItemToVest "20Rnd_762x51_Mag";};
this addHeadgear "H_Booniehat_mcamo";
this addWeapon "srifle_EBR_F";
this addPrimaryWeaponItem "acc_pointer_IR";
this addPrimaryWeaponItem "optic_SOS";
this addPrimaryWeaponItem "bipod_01_F_snd";
this addWeapon "hgun_P07_F";
this addWeapon "Rangefinder";
this linkItem "ItemMap";
this linkItem "ItemCompass";
this linkItem "ItemWatch";
this linkItem "ItemRadio";
this linkItem "ItemGPS";
this linkItem "NVGoggles";
