this = _this select 0;
if (!local this) exitWith {};

removeAllWeapons this;
removeAllItems this;
removeAllAssignedItems this;
removeUniform this;
removeVest this;
removeBackpack this;
removeHeadgear this;
removeGoggles this;
this forceAddUniform "U_B_HeliPilotCoveralls";
this addItemToUniform "B_IR_Grenade";
for "_i" from 1 to 2 do {this addItemToUniform "SmokeShell";};
for "_i" from 1 to 2 do {this addItemToUniform "HandGrenade";};
for "_i" from 1 to 2 do {this addItemToUniform "Chemlight_blue";};
this addVest "V_BandollierB_oli";
for "_i" from 1 to 4 do {this addItemToVest "FirstAidKit";};
this addItemToVest "16Rnd_9x21_Mag";
for "_i" from 1 to 4 do {this addItemToVest "30Rnd_45ACP_Mag_SMG_01";};
this addHeadgear "H_PilotHelmetHeli_B";
this addWeapon "SMG_01_F";
this addPrimaryWeaponItem "optic_Aco_smg";
this addWeapon "hgun_P07_F";
this addWeapon "Binocular";
this linkItem "ItemMap";
this linkItem "ItemCompass";
this linkItem "ItemWatch";
this linkItem "ItemRadio";
this linkItem "ItemGPS";
this linkItem "NVGoggles";
